services:
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: web-app
    ports:
      - '3300:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
