import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

/**
 * TODO: Replace Roboto with Felix when available.
 */
const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} `}>{children}</body>
    </html>
  );
}
